web/router.ex
defmodule Syndeo.Router do
  use Syndeo.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    if Mix.env == :test do
      plug Syndeo.Plug.SessionBackdoor
    end
    plug Syndeo.TokenVerifier
    plug Syndeo.AttendeeSession
    plug Doorman.Login.Session
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  scope "/", Syndeo do
    pipe_through [:browser]
    resources "/session", SessionController, only: [:new, :create, :delete], singleton: true
    resources "/attendees", AttendeeController, only: [:new, :create]
    get "/", AttendeeController, :new
    resources "/tokenized_email", TokenizedEmailController, only: [:create]
    resources "/ics", IcsController, only: [:show]
  end

  scope "/", Syndeo do
    pipe_through [:browser, Syndeo.RequireAttendee]
    resources "/attendees", AttendeeController, only: [:show, :edit, :update, :delete] do
      resources "/weekly_info", WeeklyInfoController, only: [:new, :create, :index, :delete]
    end
  end

  scope "/admin", Syndeo, as: :admin do
    pipe_through [:browser, Syndeo.RequireAdmin]
    resources "/users", Admin.UserController, only: [:index, :create, :new, :edit, :update, :delete]
    resources "/attendees", Admin.AttendeeController, only: [:index, :edit, :delete, :show]
    resources "/meals", Admin.MealController
    resources "/weekly_info", Admin.WeeklyInfoController, only: [:index]
  end
end

web/views/layout_view.ex
defmodule Syndeo.LayoutView do
  use Syndeo.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SMCC's Online Connection Card!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <script src="https://use.fontawesome.com/82c93ec4ce.js"></script>
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= if @conn.assigns[:current_user] do %>
              <div class="dropdown pull-right">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin Menu<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link "Current Week", to: admin_weekly_info_path(@conn, :index) %></li>
                  <li><%= link "Attendees", to: admin_attendee_path(@conn, :index) %></li>
                  <li><%= link "Meals", to: admin_meal_path(@conn, :index) %></li>
                </ul>
              </div>
            <% else %>
                <li><%= link "Admin Sign In", to: session_path(@conn, :new) %></li>
            <% end %>
          </ul>
          <ul class="nav nav-pills pull-left">
            <%= if @conn.assigns[:current_attendee] do %>
              <li>Welcome,<br /><%= @current_attendee.name %>!</li>
              <li><%= link "Connect", to: attendee_weekly_info_path(@conn, :index, @current_attendee.id), class: "btn btn-xs btn-default" %></li>
            <% end %>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/email.html.eex
<%= render @view_module, @view_template, assigns %>

web/templates/layout/email.text.eex
<%= render @view_module, @view_template, assigns %>