web/router.ex
defmodule Syndeo.Router do
  use Syndeo.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    if Mix.env == :test do
      plug Syndeo.Plug.SessionBackdoor
    end
    plug Syndeo.TokenVerifier
    plug Syndeo.AttendeeSession
    plug Doorman.Login.Session
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  scope "/", Syndeo do
    pipe_through [:browser]
    resources "/session", SessionController, only: [:new, :create, :delete], singleton: true
    resources "/attendees", AttendeeController, only: [:new, :create]
    get "/", AttendeeController, :new
    resources "/tokenized_email", TokenizedEmailController, only: [:create]
    resources "/ics", IcsController, only: [:show]
  end

  scope "/", Syndeo do
    pipe_through [:browser, Syndeo.RequireAttendee]
    resources "/attendees", AttendeeController, only: [:show, :edit, :update, :delete] do
      resources "/weekly_info", WeeklyInfoController, only: [:new, :create, :index, :delete]
    end
  end

  scope "/admin", Syndeo, as: :admin do
    pipe_through [:browser, Syndeo.RequireAdmin]
    resources "/users", Admin.UserController, only: [:index, :create, :new, :edit, :update, :delete]
    resources "/attendees", Admin.AttendeeController, only: [:index, :edit, :delete, :show]
    resources "/meals", Admin.MealController
    resources "/weekly_info", Admin.WeeklyInfoController, only: [:index]
  end
end

web/models/weekly_info.ex
defmodule Syndeo.WeeklyInfo do
  use Syndeo.Web, :model

  schema "weeklyinfo" do
    field :week_date, Timex.Ecto.Date
    field :attending_meal, :boolean, default: false
    field :num_kids, :integer
    field :num_teens, :integer
    field :num_adults, :integer
    field :prayers, :string
    field :contact, :string
    field :service, :string
    belongs_to :attendee, Syndeo.Attendee, type: :binary_id

    timestamps()
  end

  defp required_fields do
    ~w(
       attendee_id
       week_date
       attending_meal
       service
     )a
  end

  defp optional_fields do
    ~w(
       num_kids
       num_teens
       num_adults
       prayers
       contact
     )a
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, required_fields() ++ optional_fields())
    |> validate_required(required_fields())
  end

  def contact_options do
    [
      "Becoming a follower of Christ",
      "Church membership",
      "I'd like a visit or call from the pastor",
      "Serving at SMCC",
      "Other (Please specify in the comments section)"
    ]
  end

  def services do
    [
      "10:30"
    ]
  end

  def display_last_sunday do
    Timex.format!(
    Timex.beginning_of_week(Timex.today, :sun),
    "%m-%d-%Y",
    :strftime
  )
  end

  def week_of do
    today = Timex.today
    lastsun = Timex.beginning_of_week(Timex.today, :sun)
    nextsun = Timex.beginning_of_week(Timex.shift(today, days: 7), :sun)

    if Timex.diff(today, lastsun, :days) < 4 do
      lastsun
    else
      nextsun
    end
  end
end

web/controllers/admin/weekly_info_controller.ex
defmodule Syndeo.Admin.WeeklyInfoController do
  use Syndeo.Web, :controller
  import Syndeo.AttendeeQuery

  def index(conn, _params) do
    attendees = find_attendees_with_current_week_info()

    conn
    |> assign(:attendees, attendees)
    |> render(:index)
  end
end

web/controllers/weekly_info_controller.ex
defmodule Syndeo.WeeklyInfoController do
  use Syndeo.Web, :controller
  alias Syndeo.WeeklyInfo
  alias Syndeo.Attendee
  alias Syndeo.AttendeeEmail
  alias Syndeo.Mailer
  import Syndeo.AttendeeQuery
  import Syndeo.MealQuery

  def index(conn, %{"attendee_id" => attendee_id}) do
    attendee = find_attendee!(attendee_id)
    meal = find_meal()
    changeset = WeeklyInfo.changeset(%WeeklyInfo{})

    conn
    |> render_index(attendee, meal, changeset)
  end

  def create(conn, %{"attendee_id" => attendee_id, "weekly_info" => weekly_info_params}) do
    params = Map.merge(weekly_info_params, %{"attendee_id" => attendee_id})
    meal = find_meal()
    attendee = find_attendee!(attendee_id)
    changeset = WeeklyInfo.changeset(%WeeklyInfo{}, params)

    case Repo.insert(changeset) do
      {:ok, weekly_info} ->
        weekly_info
        |> AttendeeEmail.weekly_email(attendee, meal)
        |> Mailer.deliver_later

        conn
        |> put_flash(:info, gettext("We've added your info for this week."))
        |> redirect(to: attendee_weekly_info_path(conn, :index, attendee_id))
      {:error, changeset} ->
        attendee = find_attendee!(attendee_id)

        conn
        |> render_index(attendee, meal, changeset)
    end
  end

  def delete(conn, %{"attendee_id" => attendee_id, "id" => weekly_info_id}) do
    WeeklyInfo
    |> where(attendee_id: ^attendee_id, id: ^weekly_info_id)
    |> Repo.one
    |> Repo.delete!

    conn
    |> put_flash(:info, gettext("This week's info has been removed."))
    |> redirect(to: attendee_weekly_info_path(conn, :index, attendee_id))
  end

  defp render_index(conn, %Attendee{}=attendee, meal, changeset) do
    conn
    |> assign(:attendee, attendee)
    |> assign(:weekly_info, attendee.weekly_info)
    |> assign(:meal, meal)
    |> assign(:changeset, changeset)
    |> render(:index)
  end
end

web/views/admin/weekly_info_view.ex
defmodule Syndeo.Admin.WeeklyInfoView do
  use Syndeo.Web, :view
end

web/views/weekly_info_view.ex
defmodule Syndeo.WeeklyInfoView do
  use Syndeo.Web, :view

  def to_display(true), do: "Yes"
  def to_display(false), do: "No"
  def display_date(date) do
    Timex.format!(date, "%m-%d-%Y", :strftime)
  end
end

web/templates/weekly_info/form.html.eex
<%= form_for @changeset, attendee_weekly_info_path(@conn, :create, @attendee), fn f -> %>
  <%= render Syndeo.FormView, "_form_errors.html", changeset: @changeset, form: f %>
    <div class="form-group row">
      <div class="col-sm-2">
        <%= label f, :week_date, gettext("Week of:") %>
      </div>
      <div class="col-sm-6">
        <%= input f, :week_date, class: "form-control", label: false, value: Syndeo.WeeklyInfo.week_of() %>
      </div>
    </div>

  <div class="form-group row">
    <div class="col-sm-8">
      <%= select(f, :service, Syndeo.WeeklyInfo.services, prompt: "Service Time", class: "form-control") %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-8">
      <%= label f, :contact, gettext("Please contact me about...") %>
      <%= select(f, :contact, Syndeo.WeeklyInfo.contact_options, class: "form-control") %>
    </div>
  </div>
  <div class="form-group row divider">
    <div class="col-sm-8">
      <%= label f, :prayers, "Prayer requests or comments" %>
      <%= input f, :prayers, class: "form-control", as: :textarea, rows: 6 %>
    </div>
  </div>

  <%= if @meal.description == "No Meal" do %>
    <div class="form-group row">
      <div class="col-sm-8">
        <strong> &#42; There will be no Wednesday night meal this week.</strong>
      </div>
    </div>
  <% else %>
    <div class="form-group row">
      <div class="col-sm-8">
        The meal for this week will be <%= @meal.description %>.
        <%= link to: ics_path(@conn, :show, @meal) do %>
          <i class="fa fa-calendar" aria-hidden="true" title="Add to calendar" style="font-size:1.75em;"></i>
        <% end %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-8">
        <%= label f, :attending_meal, gettext("Will you be attending Wednesday's meal?") %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-2">
        <%= select(f, :attending_meal, ["Yes": true, "No": false], id: "attending", class: "form-control") %>
      </div>
    </div>
    <div id="headcounts">
      <div class="form-group row">
        <div class="col-sm-8">
          Please enter how many will be attending:<br />
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-2">
          <%= input f, :num_kids, class: "form-control", as: :number, label: false, placeholder: "kids" %>
        </div>
        <div class="col-sm-2">
          <%= input f, :num_teens, class: "form-control", as: :number, label: false, placeholder: "teens" %>
        </div>
        <div class="col-sm-2">
          <%= input f, :num_adults, class: "form-control", as: :number, label: false, placeholder: "adults" %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/weekly_info/index.html.eex
<%= render "form.html", changeset: @changeset, conn: @conn, attendee: @attendee, meal: @meal %>

<h3>Previous weeks</h3>
<%= if Enum.any?(@weekly_info) do %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Week date</th>
        <th>Service Attended</th>
        <th>Wednesday Meal</th>
        <th>Prayers</th>

        <th></th>
      </tr>
    </thead>
    <tbody>
  <%= for weekly_info <- @weekly_info do %>
      <tr>
        <td>
          <%= weekly_info.week_date |> display_date %>
        </td>
        <td><%= weekly_info.service %></td>
        <td><%= weekly_info.attending_meal |> to_display %></td>
        <td><%= weekly_info.prayers %></td>
        <td class="text-right">
          <%= link(
            "X",
            to: attendee_weekly_info_path(@conn, :delete, @attendee, weekly_info),
            method: :delete,
            data: [confirm: "Are you sure you want to remove this?"],
            class: "btn-xs btn-danger"
          ) %>
        </td>
      </tr>
  <% end %>
    </tbody>
  </table>
<% else %>
  <p>This is your first week... thank you for participating!</p>
<% end%>